//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trivial.Chemistry {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChemistryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChemistryResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trivial.Chemistry.ChemistryResource", typeof(ChemistryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Chemical element 的本地化字符串。
        /// </summary>
        internal static string ChemicalElement {
            get {
                return ResourceManager.GetString("ChemicalElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chemistry 的本地化字符串。
        /// </summary>
        internal static string Chemistry {
            get {
                return ResourceManager.GetString("Chemistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Element 的本地化字符串。
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Hydrogen 的本地化字符串。
        /// </summary>
        internal static string Element001 {
            get {
                return ResourceManager.GetString("Element001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Helium 的本地化字符串。
        /// </summary>
        internal static string Element002 {
            get {
                return ResourceManager.GetString("Element002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Lithium 的本地化字符串。
        /// </summary>
        internal static string Element003 {
            get {
                return ResourceManager.GetString("Element003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Beryllium 的本地化字符串。
        /// </summary>
        internal static string Element004 {
            get {
                return ResourceManager.GetString("Element004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Boron 的本地化字符串。
        /// </summary>
        internal static string Element005 {
            get {
                return ResourceManager.GetString("Element005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Carbon 的本地化字符串。
        /// </summary>
        internal static string Element006 {
            get {
                return ResourceManager.GetString("Element006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Nitrogen 的本地化字符串。
        /// </summary>
        internal static string Element007 {
            get {
                return ResourceManager.GetString("Element007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Oxygen 的本地化字符串。
        /// </summary>
        internal static string Element008 {
            get {
                return ResourceManager.GetString("Element008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Fluorine 的本地化字符串。
        /// </summary>
        internal static string Element009 {
            get {
                return ResourceManager.GetString("Element009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Neon 的本地化字符串。
        /// </summary>
        internal static string Element010 {
            get {
                return ResourceManager.GetString("Element010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Sodium 的本地化字符串。
        /// </summary>
        internal static string Element011 {
            get {
                return ResourceManager.GetString("Element011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Magnesium 的本地化字符串。
        /// </summary>
        internal static string Element012 {
            get {
                return ResourceManager.GetString("Element012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Aluminium 的本地化字符串。
        /// </summary>
        internal static string Element013 {
            get {
                return ResourceManager.GetString("Element013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Silicon 的本地化字符串。
        /// </summary>
        internal static string Element014 {
            get {
                return ResourceManager.GetString("Element014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Phosphorus 的本地化字符串。
        /// </summary>
        internal static string Element015 {
            get {
                return ResourceManager.GetString("Element015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Sulfur 的本地化字符串。
        /// </summary>
        internal static string Element016 {
            get {
                return ResourceManager.GetString("Element016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Chlorine 的本地化字符串。
        /// </summary>
        internal static string Element017 {
            get {
                return ResourceManager.GetString("Element017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Argon 的本地化字符串。
        /// </summary>
        internal static string Element018 {
            get {
                return ResourceManager.GetString("Element018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Potassium 的本地化字符串。
        /// </summary>
        internal static string Element019 {
            get {
                return ResourceManager.GetString("Element019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Calcium 的本地化字符串。
        /// </summary>
        internal static string Element020 {
            get {
                return ResourceManager.GetString("Element020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Scandium 的本地化字符串。
        /// </summary>
        internal static string Element021 {
            get {
                return ResourceManager.GetString("Element021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Titanium 的本地化字符串。
        /// </summary>
        internal static string Element022 {
            get {
                return ResourceManager.GetString("Element022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Vanadium 的本地化字符串。
        /// </summary>
        internal static string Element023 {
            get {
                return ResourceManager.GetString("Element023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Chromium 的本地化字符串。
        /// </summary>
        internal static string Element024 {
            get {
                return ResourceManager.GetString("Element024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Manganese 的本地化字符串。
        /// </summary>
        internal static string Element025 {
            get {
                return ResourceManager.GetString("Element025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Iron 的本地化字符串。
        /// </summary>
        internal static string Element026 {
            get {
                return ResourceManager.GetString("Element026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Cobalt 的本地化字符串。
        /// </summary>
        internal static string Element027 {
            get {
                return ResourceManager.GetString("Element027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Nickel 的本地化字符串。
        /// </summary>
        internal static string Element028 {
            get {
                return ResourceManager.GetString("Element028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Copper 的本地化字符串。
        /// </summary>
        internal static string Element029 {
            get {
                return ResourceManager.GetString("Element029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Zinc 的本地化字符串。
        /// </summary>
        internal static string Element030 {
            get {
                return ResourceManager.GetString("Element030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Gallium 的本地化字符串。
        /// </summary>
        internal static string Element031 {
            get {
                return ResourceManager.GetString("Element031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Germanium 的本地化字符串。
        /// </summary>
        internal static string Element032 {
            get {
                return ResourceManager.GetString("Element032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Arsenic 的本地化字符串。
        /// </summary>
        internal static string Element033 {
            get {
                return ResourceManager.GetString("Element033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Selenium 的本地化字符串。
        /// </summary>
        internal static string Element034 {
            get {
                return ResourceManager.GetString("Element034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Bromine 的本地化字符串。
        /// </summary>
        internal static string Element035 {
            get {
                return ResourceManager.GetString("Element035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Krypton 的本地化字符串。
        /// </summary>
        internal static string Element036 {
            get {
                return ResourceManager.GetString("Element036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Rubidium 的本地化字符串。
        /// </summary>
        internal static string Element037 {
            get {
                return ResourceManager.GetString("Element037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Strontium 的本地化字符串。
        /// </summary>
        internal static string Element038 {
            get {
                return ResourceManager.GetString("Element038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Yttrium 的本地化字符串。
        /// </summary>
        internal static string Element039 {
            get {
                return ResourceManager.GetString("Element039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Zirconium 的本地化字符串。
        /// </summary>
        internal static string Element040 {
            get {
                return ResourceManager.GetString("Element040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Niobium 的本地化字符串。
        /// </summary>
        internal static string Element041 {
            get {
                return ResourceManager.GetString("Element041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Molybdenum 的本地化字符串。
        /// </summary>
        internal static string Element042 {
            get {
                return ResourceManager.GetString("Element042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Technetium 的本地化字符串。
        /// </summary>
        internal static string Element043 {
            get {
                return ResourceManager.GetString("Element043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Ruthenium 的本地化字符串。
        /// </summary>
        internal static string Element044 {
            get {
                return ResourceManager.GetString("Element044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Rhodium 的本地化字符串。
        /// </summary>
        internal static string Element045 {
            get {
                return ResourceManager.GetString("Element045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Palladium 的本地化字符串。
        /// </summary>
        internal static string Element046 {
            get {
                return ResourceManager.GetString("Element046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Silver 的本地化字符串。
        /// </summary>
        internal static string Element047 {
            get {
                return ResourceManager.GetString("Element047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Cadmium 的本地化字符串。
        /// </summary>
        internal static string Element048 {
            get {
                return ResourceManager.GetString("Element048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Indium 的本地化字符串。
        /// </summary>
        internal static string Element049 {
            get {
                return ResourceManager.GetString("Element049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Tin 的本地化字符串。
        /// </summary>
        internal static string Element050 {
            get {
                return ResourceManager.GetString("Element050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Antimony 的本地化字符串。
        /// </summary>
        internal static string Element051 {
            get {
                return ResourceManager.GetString("Element051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Tellurium 的本地化字符串。
        /// </summary>
        internal static string Element052 {
            get {
                return ResourceManager.GetString("Element052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Iodine 的本地化字符串。
        /// </summary>
        internal static string Element053 {
            get {
                return ResourceManager.GetString("Element053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Xenon 的本地化字符串。
        /// </summary>
        internal static string Element054 {
            get {
                return ResourceManager.GetString("Element054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Caesium 的本地化字符串。
        /// </summary>
        internal static string Element055 {
            get {
                return ResourceManager.GetString("Element055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Barium 的本地化字符串。
        /// </summary>
        internal static string Element056 {
            get {
                return ResourceManager.GetString("Element056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Lanthanum 的本地化字符串。
        /// </summary>
        internal static string Element057 {
            get {
                return ResourceManager.GetString("Element057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Cerium 的本地化字符串。
        /// </summary>
        internal static string Element058 {
            get {
                return ResourceManager.GetString("Element058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Praseodymium 的本地化字符串。
        /// </summary>
        internal static string Element059 {
            get {
                return ResourceManager.GetString("Element059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Neodymium 的本地化字符串。
        /// </summary>
        internal static string Element060 {
            get {
                return ResourceManager.GetString("Element060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Promethium 的本地化字符串。
        /// </summary>
        internal static string Element061 {
            get {
                return ResourceManager.GetString("Element061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Samarium 的本地化字符串。
        /// </summary>
        internal static string Element062 {
            get {
                return ResourceManager.GetString("Element062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Europium 的本地化字符串。
        /// </summary>
        internal static string Element063 {
            get {
                return ResourceManager.GetString("Element063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Gadolinium 的本地化字符串。
        /// </summary>
        internal static string Element064 {
            get {
                return ResourceManager.GetString("Element064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Terbium 的本地化字符串。
        /// </summary>
        internal static string Element065 {
            get {
                return ResourceManager.GetString("Element065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Dysprosium 的本地化字符串。
        /// </summary>
        internal static string Element066 {
            get {
                return ResourceManager.GetString("Element066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Holmium 的本地化字符串。
        /// </summary>
        internal static string Element067 {
            get {
                return ResourceManager.GetString("Element067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Erbium 的本地化字符串。
        /// </summary>
        internal static string Element068 {
            get {
                return ResourceManager.GetString("Element068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Thulium 的本地化字符串。
        /// </summary>
        internal static string Element069 {
            get {
                return ResourceManager.GetString("Element069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Ytterbium 的本地化字符串。
        /// </summary>
        internal static string Element070 {
            get {
                return ResourceManager.GetString("Element070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Lutetium 的本地化字符串。
        /// </summary>
        internal static string Element071 {
            get {
                return ResourceManager.GetString("Element071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Hafnium 的本地化字符串。
        /// </summary>
        internal static string Element072 {
            get {
                return ResourceManager.GetString("Element072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Tantalum 的本地化字符串。
        /// </summary>
        internal static string Element073 {
            get {
                return ResourceManager.GetString("Element073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Tungsten 的本地化字符串。
        /// </summary>
        internal static string Element074 {
            get {
                return ResourceManager.GetString("Element074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Rhenium 的本地化字符串。
        /// </summary>
        internal static string Element075 {
            get {
                return ResourceManager.GetString("Element075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Osmium 的本地化字符串。
        /// </summary>
        internal static string Element076 {
            get {
                return ResourceManager.GetString("Element076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Iridium 的本地化字符串。
        /// </summary>
        internal static string Element077 {
            get {
                return ResourceManager.GetString("Element077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Platinum 的本地化字符串。
        /// </summary>
        internal static string Element078 {
            get {
                return ResourceManager.GetString("Element078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Gold 的本地化字符串。
        /// </summary>
        internal static string Element079 {
            get {
                return ResourceManager.GetString("Element079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Mercury 的本地化字符串。
        /// </summary>
        internal static string Element080 {
            get {
                return ResourceManager.GetString("Element080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Thallium 的本地化字符串。
        /// </summary>
        internal static string Element081 {
            get {
                return ResourceManager.GetString("Element081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Lead 的本地化字符串。
        /// </summary>
        internal static string Element082 {
            get {
                return ResourceManager.GetString("Element082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Bismuth 的本地化字符串。
        /// </summary>
        internal static string Element083 {
            get {
                return ResourceManager.GetString("Element083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Polonium 的本地化字符串。
        /// </summary>
        internal static string Element084 {
            get {
                return ResourceManager.GetString("Element084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Astatine 的本地化字符串。
        /// </summary>
        internal static string Element085 {
            get {
                return ResourceManager.GetString("Element085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Radon 的本地化字符串。
        /// </summary>
        internal static string Element086 {
            get {
                return ResourceManager.GetString("Element086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Francium 的本地化字符串。
        /// </summary>
        internal static string Element087 {
            get {
                return ResourceManager.GetString("Element087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Radium 的本地化字符串。
        /// </summary>
        internal static string Element088 {
            get {
                return ResourceManager.GetString("Element088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Actinium 的本地化字符串。
        /// </summary>
        internal static string Element089 {
            get {
                return ResourceManager.GetString("Element089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Thorium 的本地化字符串。
        /// </summary>
        internal static string Element090 {
            get {
                return ResourceManager.GetString("Element090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Protactinium 的本地化字符串。
        /// </summary>
        internal static string Element091 {
            get {
                return ResourceManager.GetString("Element091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Uranium 的本地化字符串。
        /// </summary>
        internal static string Element092 {
            get {
                return ResourceManager.GetString("Element092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Neptunium 的本地化字符串。
        /// </summary>
        internal static string Element093 {
            get {
                return ResourceManager.GetString("Element093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Plutonium 的本地化字符串。
        /// </summary>
        internal static string Element094 {
            get {
                return ResourceManager.GetString("Element094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Americium 的本地化字符串。
        /// </summary>
        internal static string Element095 {
            get {
                return ResourceManager.GetString("Element095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Curium 的本地化字符串。
        /// </summary>
        internal static string Element096 {
            get {
                return ResourceManager.GetString("Element096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Berkelium 的本地化字符串。
        /// </summary>
        internal static string Element097 {
            get {
                return ResourceManager.GetString("Element097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Californium 的本地化字符串。
        /// </summary>
        internal static string Element098 {
            get {
                return ResourceManager.GetString("Element098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Einsteinium 的本地化字符串。
        /// </summary>
        internal static string Element099 {
            get {
                return ResourceManager.GetString("Element099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Fermium 的本地化字符串。
        /// </summary>
        internal static string Element100 {
            get {
                return ResourceManager.GetString("Element100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Mendelevium 的本地化字符串。
        /// </summary>
        internal static string Element101 {
            get {
                return ResourceManager.GetString("Element101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Nobelium 的本地化字符串。
        /// </summary>
        internal static string Element102 {
            get {
                return ResourceManager.GetString("Element102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Lawrencium 的本地化字符串。
        /// </summary>
        internal static string Element103 {
            get {
                return ResourceManager.GetString("Element103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Rutherfordium 的本地化字符串。
        /// </summary>
        internal static string Element104 {
            get {
                return ResourceManager.GetString("Element104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Dubnium 的本地化字符串。
        /// </summary>
        internal static string Element105 {
            get {
                return ResourceManager.GetString("Element105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Seaborgium 的本地化字符串。
        /// </summary>
        internal static string Element106 {
            get {
                return ResourceManager.GetString("Element106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Bohrium 的本地化字符串。
        /// </summary>
        internal static string Element107 {
            get {
                return ResourceManager.GetString("Element107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Hassium 的本地化字符串。
        /// </summary>
        internal static string Element108 {
            get {
                return ResourceManager.GetString("Element108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Meitnerium 的本地化字符串。
        /// </summary>
        internal static string Element109 {
            get {
                return ResourceManager.GetString("Element109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Darmstadtium 的本地化字符串。
        /// </summary>
        internal static string Element110 {
            get {
                return ResourceManager.GetString("Element110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Roentgenium 的本地化字符串。
        /// </summary>
        internal static string Element111 {
            get {
                return ResourceManager.GetString("Element111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Copernicium 的本地化字符串。
        /// </summary>
        internal static string Element112 {
            get {
                return ResourceManager.GetString("Element112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Nihonium 的本地化字符串。
        /// </summary>
        internal static string Element113 {
            get {
                return ResourceManager.GetString("Element113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Flerovium 的本地化字符串。
        /// </summary>
        internal static string Element114 {
            get {
                return ResourceManager.GetString("Element114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Moscovium 的本地化字符串。
        /// </summary>
        internal static string Element115 {
            get {
                return ResourceManager.GetString("Element115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Livermorium 的本地化字符串。
        /// </summary>
        internal static string Element116 {
            get {
                return ResourceManager.GetString("Element116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Tennessine 的本地化字符串。
        /// </summary>
        internal static string Element117 {
            get {
                return ResourceManager.GetString("Element117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Oganesson 的本地化字符串。
        /// </summary>
        internal static string Element118 {
            get {
                return ResourceManager.GetString("Element118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ElementX {
            get {
                return ResourceManager.GetString("ElementX", resourceCulture);
            }
        }
    }
}
